name: PraxiCloud Distributed Build Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-library:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
        source-url: ${{secrets.REPO_NUGET_SOURCE}}
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        NUGET_SOURCE: ${{secrets.REPO_NUGET_SOURCE}}
        NUGET_USER: ${{secrets.REPO_USER_NAME}}
    - name: Update Packaging Version
      run: sed -i "s/<Version>1.0.1<\/Version>/<Version>1.3.$(date +%Y)$(date +%m)$(date +%d).$GITHUB_RUN_NUMBER<\/Version>/g" ./src/common.props      
    - name: Install Nuget Dependencies
      run: dotnet restore ./src/praxicloud.distributed.solution.sln
    - name: Build Library and Test Projects
      run: dotnet build --configuration Release --no-restore ./src/praxicloud.distributed.solution.sln
    - name: Test Library
      run: dotnet test --no-restore --verbosity normal ./src/praxicloud.distributed.tests/praxicloud.distributed.tests.csproj
    - name: Package library
      run: dotnet pack --configuration Release ./src/praxicloud.distributed/praxicloud.distributed.csproj
    - name: Push library package to GitHub NUGET Feed
      run: nuget push ./src/praxicloud.distributed/bin/Release/*.nupkg -SkipDuplicate -ApiKey ${{secrets.GITHUB_TOKEN}}  
